[project]
name = "time-series-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas==3.0.0",
    "matplotlib==3.10.8",
    "scikit-learn==1.8.0",
    "statsmodels==0.14.6",
    "ipykernel==7.2.0"
]
